name: hpc_assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - annotated-types=0.7.0
  - anyio=4.12.1
  - asgiref=3.11.0
  - async-timeout=4.0.3
  - attrs=25.4.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backoff=2.2.1
  - bcrypt=5.0.0
  - beautifulsoup4=4.14.3
  - blas=2.305
  - blas-devel=3.11.0
  - blinker=1.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - cpython=3.10.19
  - cryptography=46.0.3
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - datasets=2.14.4
  - deprecated=1.3.1
  - dill=0.3.7
  - distro=1.9.0
  - dnspython=2.8.0
  - durationpy=0.10
  - email-validator=2.3.0
  - email_validator=2.3.0
  - exceptiongroup=1.3.1
  - expat=2.7.3
  - fastapi=0.115.9
  - fastapi-cli=0.0.20
  - filelock=3.20.2
  - fsspec=2025.12.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.47.0
  - googleapis-common-protos=1.72.0
  - greenlet=3.3.0
  - grpcio=1.71.0
  - h11=0.16.0
  - h2=4.3.0
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - huggingface_hub=0.36.0
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - langchain=1.2.1
  - langchain-core=1.2.6
  - langchain-ollama=1.0.1
  - langgraph=1.0.5
  - langgraph-checkpoint=3.0.1
  - langgraph-prebuilt=1.0.5
  - langgraph-sdk=0.3.1
  - langsmith=0.6.1
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libblas=3.11.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcufft=11.4.1.4
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusparse=12.5.10.65
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libnvjitlink=12.9.86
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.19.0
  - libopentelemetry-cpp-headers=1.19.0
  - libparquet=19.0.1
  - libpng=1.6.53
  - libprotobuf=5.29.3
  - libpulsar=3.7.2
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.7.0
  - libutf8proc=2.10.0
  - libuuid=1.41.5
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - mmh3=5.2.0
  - monotonic=1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - nomkl=1.0
  - numpy=2.2.6
  - oauthlib=3.3.1
  - ollama-python=0.6.1
  - openblas=0.3.30
  - openjpeg=2.5.3
  - openssl=3.6.0
  - opentelemetry-api=1.39.1
  - opentelemetry-exporter-otlp-proto-common=1.39.1
  - opentelemetry-exporter-otlp-proto-grpc=1.39.1
  - opentelemetry-instrumentation=0.60b1
  - opentelemetry-instrumentation-asgi=0.60b1
  - opentelemetry-instrumentation-fastapi=0.60b1
  - opentelemetry-proto=1.39.1
  - opentelemetry-sdk=1.39.1
  - opentelemetry-semantic-conventions=0.60b1
  - opentelemetry-util-http=0.60b1
  - orc=2.1.1
  - orjson=3.11.5
  - ormsgpack=1.12.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pillow=11.3.0
  - pip=25.3
  - posthog=5.4.0
  - prometheus-cpp=1.3.0
  - protobuf=5.29.3
  - pthread-stubs=0.3
  - pulsar-client=3.8.0
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybase64=1.4.3
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyopenssl=25.3.0
  - pypika=0.48.9
  - pyproject_hooks=1.2.0
  - pysocks=1.7.1
  - python=3.10.19
  - python-build=1.3.0
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-flatbuffers=25.9.23
  - python-gil=3.10.19
  - python-kubernetes=34.1.0
  - python-multipart=0.0.21
  - python-tzdata=2025.3
  - python-xxhash=3.6.0
  - python_abi=3.10
  - pytorch=2.7.0
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.3
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.37.0
  - regex=2025.11.3
  - requests=2.32.5
  - requests-oauthlib=2.0.0
  - requests-toolbelt=1.0.0
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - rpds-py=0.30.0
  - rsa=4.9.1
  - s2n=1.5.14
  - safetensors=0.7.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - sentence-transformers=5.2.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8.1
  - sqlalchemy=2.0.45
  - sqlite=3.51.1
  - starlette=0.45.3
  - sympy=1.14.0
  - tenacity=9.1.2
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tokenizers=0.22.2
  - tomli=2.3.0
  - tqdm=4.67.1
  - transformers=4.57.3
  - typer=0.21.1
  - typer-slim=0.21.1
  - typer-slim-standard=0.21.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uuid-utils=0.12.0
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - websocket-client=1.9.0
  - websockets=15.0.1
  - wheel=0.45.1
  - wrapt=1.17.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - chromadb==1.4.0
      - dataclasses-json==0.6.7
      - frozenlist==1.8.0
      - httpx-sse==0.4.3
      - langchain-chroma==1.1.0
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-text-splitters==1.1.0
      - marshmallow==3.26.2
      - mypy-extensions==1.1.0
      - onnxruntime==1.23.2
      - propcache==0.4.1
      - pydantic-settings==2.12.0
      - typing-inspect==0.9.0
      - urllib3==2.6.3
      - zstandard==0.25.0
prefix: /umbc/rs/pi_gobbert/users/elliotg2/conda_envs/hpc_assistant
